default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password:
  host: db

development:
  <<: *default
  database: olive-way-dev

test:
  <<: *default
  database: olive-way-test
