default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password:

development:
  <<: *default
  database: db/olive-way-dev

test:
  <<: *default
  database: db/olive-way-test

production:
  <<: *default
  database: db/olive-way-prod
